version: "3.7"

services:
  wootrico:
    image: ericoautomacao/wootrico
    environment:
      
      - PORT=3000
      - LOG_LEVEL=info
      
      - WEBHOOK_BASE_URL=https://wootrico.cursoautonext.com.br
      - WEBHOOK_NAME=wootrico

      - CHATWOOT_BASE_URL=https://chat.cursoautonext.com.br/
      - CHATWOOT_API_TOKEN=ZaPYpPpU8GxsCAen4t5Y8H44
      - CHATWOOT_ACCOUNT_ID=1

      - CHATWOOT_INBOX_NAME=Wootrico

      - APP_DATA_FILE=/app/data/app-data.json
      - DEFAULT_COUNTRY=BR
      - NATS_URL=nats://nats:4222     



      # Configuração UAZAPI
      #- UAZAPI_BASE_URL=https://free.uazapi.com
      #- UAZAPI_TOKEN=94fb01fe-c00a-4bb1-abe2-908999c8a9d7
      
      # Configuração WuZAPI
      #- WUZAPI_BASE_URL=https://apiwuzapi.cursoautonext.com.br/
      #- WUZAPI_TOKEN=hXEJy7GFHf3KJkuHzd4w      
      
      # Configuração Z-API 
      - ZAPI_INSTANCIA=3E02793370CEB042B3604AF752FBD4C9
      - ZAPI_TOKEN_INSTANCIA=F4C2DC7613C99B35FB9B3AB0
      - ZAPI_CLIENT_TOKEN=F23d562cc477a4fc1bf98e09489972463S      
      
    ports:
      - 3000:3000
    networks:
      - erico-net-desenv
    volumes:
      - wootrico-data:/app/data
    # Configura o Modo de Deploy da Aplicação
    deploy:
      # Configura o modo de deploy
      mode: replicated
      # Configura o numero de replicas
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      resources:
        limits:          
          cpus: "1"          
          memory: 800M
      labels:
        # Configura o Roteamento do Traefik
        # habilita o traefik
        - traefik.enable=true 
        # Configura o Roteamento do Traefik para o Chatwoot
        - traefik.http.routers.wootrico.rule=Host(`wootrico.cursoautonext.com.br`)
        # Define o tipo de entrada para HTTPS
        - traefik.http.routers.wootrico.entrypoints=websecure
        # Define o certificado
        - traefik.http.routers.wootrico.tls.certresolver=letsencryptresolver
        # Define o serviço do Chatwoot
        - traefik.http.routers.wootrico.service=wootrico
        # Define a porta do Chatwoot
        - traefik.http.services.wootrico.loadbalancer.server.port=3000
        # Define os Headers do Chatwoot
        - traefik.http.services.wootrico.loadbalancer.passhostheader=true

volumes:
  wootrico-data:
    external: true
    name: wootrico-data

# Rede overlay externa usada em todo o cluster AutoNext
networks:
  erico-net-desenv:
    external: true
    name: erico-net-desenv