version: '3.7'

services:
  wuzapi-server:
    image: asternic/wuzapi:latest

    networks:
      - erico-net-desenv
    environment:
      - WUZAPI_ADMIN_TOKEN=OJ8gvybdRN3pSHYamWAT4
      - DB_USER=postgres
      - DB_PASSWORD=dat3HJbXULMSKa7MajRR82hZI
      - DB_NAME=wuzapi
      - DB_HOST=postgres
      - DB_PORT=5432
      - TZ=America/Sao_Paulo
      - WEBHOOK_FORMAT=json
      - SESSION_DEVICE_NAME=WuzAPI
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      labels:
        - traefik.enable=true
        - traefik.http.routers.wuzapi-server.rule=Host(`apiwuzapi.cursoautonext.com.br`)
        - traefik.http.routers.wuzapi-server.entrypoints=websecure
        - traefik.http.routers.wuzapi-server.priority=1
        - traefik.http.routers.wuzapi-server.tls.certresolver=letsencryptresolver
        - traefik.http.routers.wuzapi-server.service=wuzapi-server
        - traefik.http.services.wuzapi-server.loadbalancer.server.port=8080
    

networks:
  erico-net-desenv:
    external: true
    name: erico-net-desenv